##########################################
## Properties that are fixed by DEV		##
##########################################

# Config Swagger (only for display)
fr.lh.resultsmanager.version=@project.version@
springdoc.swagger-ui.path=/index.html

# Hibernate
spring.jpa.hibernate.ddl-auto=validate

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml