##########################################
## Properties that are fixed by OPS		##
##########################################

# LOGS
logging.level.root= INFO
logging.level.fr.lh.resultsmanager=DEBUG

# Postgre
spring.datasource.url=jdbc:postgresql://localhost:5432/results_manager_db
spring.datasource.username=admin
spring.datasource.password=admin